name: Micipedia
favicon: null
layout_spectrum: 0
typography_spectrum: 0.99253
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffbe9e'
    - '#0083af'
    - '#8fa4a4'
    - '#2f8eac'
    - '#bcaea2'
  brandStrength: 0.5
  lightness: 0.45151854725554585
  saturation: 0.6577256848104298
  rhythmicContrast: 0.5492268560919911
purpose: []
